name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --no-immutable

      # 确保 CNAME 文件存在
      - name: Setup Custom Domain
        run: |
          if [ ! -f static/CNAME ]; then
            echo "hyperlane.cc" > static/CNAME
            echo "Created CNAME file"
          fi

      - name: Build website
        run: yarn build

      - name: Verify CNAME
        run: cat build/CNAME # 确认文件存在且内容正确

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
